### PR TITLE
custom delimiters

### PR DESCRIPTION
**Pull request by ulanivan**
petite-vue is convenient to embed in projects with template engines, for example, smarty. But it would be more convenient to use your custom delimiters, which the template engine can parse.

### CODE REVIEW

**Comment by stancl** [comment]
Most templating engines let you use the delimiters as raw strings. E.g. Laravel Blade uses `{{ }}` but `@{{ foo }}` is turned into raw `{{ foo }}`.

**Comment by niutech** [comment]
E.g. Smarty has [`{literal}`](https://www.smarty.net/docs/en/language.function.literal.tpl) tags to escape parsing its delimiters.

**Comment by ulanivan** [comment]
Thanks for the advice! I already found out about smarty and laravel :). But I thought that my addition would be useful not only in these cases.

**Comment by engram-design** [comment]
I'll add my plus one here, using Twig, its a bit of a pain, and for Vue, we often include:

```
delimiters: ['${', '}'],
```

Just because its easier to configure in Vue, than in Twig.

**Comment by Feiox** [comment]
This is very valuable for user who use template language of python or php.

+ 1

**Comment by ksamuel** [comment]
Same here, you currently can't use petite-vue with django because it would make one use `verbatime` everywhere in the template, which would defeat the purpose of something simple. So right now we have to stay on vue.

**Comment by yyx990803** [comment]
Thanks for the PR. It's a bit inefficient to construct a new regex on every text node visit, so I moved the logic to app context creation so it's done only once per app. See eda903c

**Pull request closed without merging**
